//ACCESS MODIFIERS--->>
// 1) PUBLIC-- CAN BE ACCESS FROM ANY class
// 2) PRIVATE -- SAME CLASS ONLY
// 3) DEFAULT-- CAN BE ACCESS IN SAME PACKAGE
// 4) PROTECTED -- NOT OUTSIDE PACKAGE BUT IN SUBCLASS OF ANY PACKAGE