// NAMING CONVENTIONS IN JAVA-->>

// RULES--
// (CAMEL CASING)-->>

// 1) CLASS AND INTERFACE -- CAPITAL LETTER EXAMPLE- Calc, Runavle
// 2) VARIABLE AND METHOD -- SMALL LETTER EXAMPLE- marks, show()
// 3) CONSTANTS -- PIE, BRAND
// 4) CONSTRUCTOR-- Human()